// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlackBookClient is the client API for BlackBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlackBookClient interface {
	GetContacts(ctx context.Context, in *ContactsRequest, opts ...grpc.CallOption) (*AddressBook, error)
}

type blackBookClient struct {
	cc grpc.ClientConnInterface
}

func NewBlackBookClient(cc grpc.ClientConnInterface) BlackBookClient {
	return &blackBookClient{cc}
}

func (c *blackBookClient) GetContacts(ctx context.Context, in *ContactsRequest, opts ...grpc.CallOption) (*AddressBook, error) {
	out := new(AddressBook)
	err := c.cc.Invoke(ctx, "/addressbook.BlackBook/GetContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlackBookServer is the server API for BlackBook service.
// All implementations must embed UnimplementedBlackBookServer
// for forward compatibility
type BlackBookServer interface {
	GetContacts(context.Context, *ContactsRequest) (*AddressBook, error)
	mustEmbedUnimplementedBlackBookServer()
}

// UnimplementedBlackBookServer must be embedded to have forward compatible implementations.
type UnimplementedBlackBookServer struct {
}

func (UnimplementedBlackBookServer) GetContacts(context.Context, *ContactsRequest) (*AddressBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContacts not implemented")
}
func (UnimplementedBlackBookServer) mustEmbedUnimplementedBlackBookServer() {}

// UnsafeBlackBookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlackBookServer will
// result in compilation errors.
type UnsafeBlackBookServer interface {
	mustEmbedUnimplementedBlackBookServer()
}

func RegisterBlackBookServer(s grpc.ServiceRegistrar, srv BlackBookServer) {
	s.RegisterService(&BlackBook_ServiceDesc, srv)
}

func _BlackBook_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackBookServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addressbook.BlackBook/GetContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackBookServer).GetContacts(ctx, req.(*ContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlackBook_ServiceDesc is the grpc.ServiceDesc for BlackBook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlackBook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "addressbook.BlackBook",
	HandlerType: (*BlackBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContacts",
			Handler:    _BlackBook_GetContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressbook.proto",
}
